// Ship module definitions for visualizer
// Generated from src/modules.py ship layouts

export const SHIP_MODULES = {
  corvette: [
    { name: "Primary Sensor Array", type: "sensor" },
    { name: "Forward Hull Section", type: "hull" },
    { name: "Command Bridge", type: "bridge" },
    { name: "Crew Quarters", type: "crew" },
    { name: "Main Reactor", type: "reactor" },
    { name: "Aft Hull Section", type: "hull" },
    { name: "Main Engine Assembly", type: "engine" },
    { name: "Fuel Tank", type: "fuel_tank" },
  ],
  frigate: [
    { name: "Primary Sensor Array", type: "sensor" },
    { name: "Forward Hull Section", type: "hull" },
    { name: "Command Bridge", type: "bridge" },
    { name: "Crew Quarters", type: "crew" },
    { name: "Central Hull Section", type: "hull" },
    { name: "Main Reactor", type: "reactor" },
    { name: "Coilgun Battery", type: "weapon" },
    { name: "Aft Hull Section", type: "hull" },
    { name: "Fuel Tank", type: "fuel_tank" },
    { name: "Main Engine Assembly", type: "engine" },
  ],
  destroyer: [
    { name: "Spinal Coiler Mount", type: "weapon" },
    { name: "Forward Hull Section", type: "hull" },
    { name: "Main Magazine", type: "magazine" },
    { name: "Dorsal Turret Mount", type: "weapon" },
    { name: "Command Bridge", type: "bridge" },
    { name: "Primary Sensor Array", type: "sensor" },
    { name: "Targeting Computer", type: "sensor" },
    { name: "Bridge Armored Bulkhead Port", type: "armor" },
    { name: "Bridge Armored Bulkhead Starboard", type: "armor" },
    { name: "Central Hull Section", type: "hull" },
    { name: "Crew Quarters", type: "crew" },
    { name: "Main Reactor", type: "reactor" },
    { name: "Reactor Armored Bulkhead Port", type: "armor" },
    { name: "Reactor Armored Bulkhead Starboard", type: "armor" },
    { name: "Aft Hull Section", type: "hull" },
    { name: "Secondary Reactor", type: "reactor" },
    { name: "Main Fuel Tank", type: "fuel_tank" },
    { name: "Reserve Fuel Tank", type: "fuel_tank" },
    { name: "PD Laser Dorsal", type: "weapon" },
    { name: "PD Laser Ventral", type: "weapon" },
    { name: "Main Engine Assembly", type: "engine" },
  ],
  cruiser: [
    { name: "Spinal Coiler Mount", type: "weapon" },
    { name: "Forward Hull Section", type: "hull" },
    { name: "Main Magazine", type: "magazine" },
    { name: "Command Bridge", type: "bridge" },
    { name: "Primary Sensor Array", type: "sensor" },
    { name: "Targeting Sensors", type: "sensor" },
    { name: "Bridge Armored Bulkhead Port", type: "armor" },
    { name: "Bridge Armored Bulkhead Starboard", type: "armor" },
    { name: "Central Hull Section", type: "hull" },
    { name: "Main Reactor", type: "reactor" },
    { name: "Reactor Armored Bulkhead Port", type: "armor" },
    { name: "Reactor Armored Bulkhead Starboard", type: "armor" },
    { name: "Aft Hull Section", type: "hull" },
    { name: "Coilgun Battery A", type: "weapon" },
    { name: "Coilgun Battery B", type: "weapon" },
    { name: "Cargo Bay", type: "cargo" },
    { name: "Crew Quarters", type: "crew" },
    { name: "Main Fuel Tank", type: "fuel_tank" },
    { name: "Main Engine Assembly", type: "engine" },
  ],
  battlecruiser: [
    { name: "Spinal Coiler Mount", type: "weapon" },
    { name: "Forward Hull Section", type: "hull" },
    { name: "Main Magazine", type: "magazine" },
    { name: "Command Bridge", type: "bridge" },
    { name: "Primary Sensor Array", type: "sensor" },
    { name: "Targeting Sensors", type: "sensor" },
    { name: "Bridge Armored Bulkhead Port", type: "armor" },
    { name: "Bridge Armored Bulkhead Starboard", type: "armor" },
    { name: "Central Hull Section", type: "hull" },
    { name: "Main Reactor", type: "reactor" },
    { name: "Reactor Armored Bulkhead Port", type: "armor" },
    { name: "Reactor Armored Bulkhead Starboard", type: "armor" },
    { name: "Aft Hull Section", type: "hull" },
    { name: "Coilgun Battery A", type: "weapon" },
    { name: "Coilgun Battery B", type: "weapon" },
    { name: "Cargo Bay", type: "cargo" },
    { name: "Crew Quarters", type: "crew" },
    { name: "Main Fuel Tank", type: "fuel_tank" },
    { name: "Main Engine Assembly", type: "engine" },
  ],
  battleship: [
    { name: "Spinal Coiler Mount", type: "weapon" },
    { name: "Forward Hull Section", type: "hull" },
    { name: "Forward Magazine", type: "magazine" },
    { name: "Heavy Coilgun Battery A", type: "weapon" },
    { name: "Heavy Coilgun Battery B", type: "weapon" },
    { name: "Command Bridge", type: "bridge" },
    { name: "Long Range Sensor Array", type: "sensor" },
    { name: "Fire Control Radar", type: "sensor" },
    { name: "Bridge Armored Bulkhead Port", type: "armor" },
    { name: "Bridge Armored Bulkhead Starboard", type: "armor" },
    { name: "Central Hull Section", type: "hull" },
    { name: "Main Fusion Reactor", type: "reactor" },
    { name: "Reactor Armored Bulkhead Port", type: "armor" },
    { name: "Reactor Armored Bulkhead Starboard", type: "armor" },
    { name: "Aft Hull Section", type: "hull" },
    { name: "Heavy Coilgun Battery C", type: "weapon" },
    { name: "Point Defense Array", type: "weapon" },
    { name: "Main Magazine", type: "cargo" },
    { name: "Crew Quarters", type: "crew" },
    { name: "Main Fuel Tank", type: "fuel_tank" },
    { name: "Reserve Fuel Tank", type: "fuel_tank" },
    { name: "Main Engine Assembly", type: "engine" },
  ],
  dreadnought: [
    { name: "Spinal Coiler Mount", type: "weapon" },
    { name: "Forward Hull Section", type: "hull" },
    { name: "Magazine Forward", type: "magazine" },
    { name: "Heavy Coilgun Battery A", type: "weapon" },
    { name: "Heavy Coilgun Battery B", type: "weapon" },
    { name: "Command Bridge", type: "bridge" },
    { name: "Long Range Sensor Array", type: "sensor" },
    { name: "Fire Control Radar", type: "sensor" },
    { name: "Combat Information Center", type: "sensor" },
    { name: "Bridge Armored Bulkhead Port", type: "armor" },
    { name: "Bridge Armored Bulkhead Starboard", type: "armor" },
    { name: "Central Hull Section", type: "hull" },
    { name: "Main Fusion Reactor", type: "reactor" },
    { name: "Secondary Reactor", type: "reactor" },
    { name: "Reactor Armored Bulkhead Port", type: "armor" },
    { name: "Reactor Armored Bulkhead Starboard", type: "armor" },
    { name: "Aft Hull Section", type: "hull" },
    { name: "Main Magazine", type: "cargo" },
    { name: "Missile Magazine", type: "cargo" },
    { name: "Main Cargo Bay", type: "cargo" },
    { name: "Crew Quarters A", type: "crew" },
    { name: "Crew Quarters B", type: "crew" },
    { name: "Heavy Coilgun Battery C", type: "weapon" },
    { name: "Heavy Coilgun Battery D", type: "weapon" },
    { name: "Point Defense Array", type: "weapon" },
    { name: "Main Fuel Tank", type: "fuel_tank" },
    { name: "Reserve Fuel Tank A", type: "fuel_tank" },
    { name: "Reserve Fuel Tank B", type: "fuel_tank" },
    { name: "Main Engine Assembly", type: "engine" },
    { name: "Maneuvering Thrusters", type: "engine" },
  ],
  // Variants use base type modules
  dreadnought_siege: null, // uses dreadnought
};

/**
 * Get modules for a ship type, handling variants
 */
export function getModulesForShipType(shipType) {
  // Handle variants (e.g., dreadnought_siege -> dreadnought)
  const baseType = shipType.split('_')[0];
  return SHIP_MODULES[shipType] || SHIP_MODULES[baseType] || SHIP_MODULES.destroyer;
}
